spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/VenueDb?createDatabaseIfNotExist=true
    username: VenueProjectUser
    password: VenueSecret12#$
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    database: postgresql
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 75993669012-nlf8nu0ip55es65019aap3n4tbstmrm0.apps.googleusercontent.com
            clientSecret: OlUyBSnKdIMU3oxVWsZ-u4mX
            redirectUriTemplate: "{baseUrl}/login/oauth2/code{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 931451027228321
            clientSecret: 82348f5499410f2daf6e09580a5ce228
            redirectUriTemplate: "{baseUrl}/login/oauth2/code{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v5.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v5.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v5.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:4200/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
#server:
#  servlet:
#    context-path: "/api"
